import Vue from "vue";
import config from "./config.js";
import "./ditto.css";
import "./error-alert.js";
import "./index.css";
import "./polyfill.NodeList.forEach.js";
import "./我的侧边栏.css";
import "./样式.css";
export declare const initloadingid: string;
declare const ApphomeVm: Vue;
export declare function mount(el: Element): void;
export { ApphomeVm };
export { config };
